### ISSUE TITLE
Link that breaks the program

### ISSUE THREAD

**Issue by justindhillon** [justindhillon/project-scanner#41]
The link:

https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/geekan/MetaGPT

The error:

node:_http_client:183
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
    ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "vscode:" not supported. Expected "http:"
    at new ClientRequest (node:_http_client:183:11)
    at Object.request (node:http:103:10)
    at ne.send_request (/home/justin/Git/link-inspector/dist/index.js:24:429723)
    at ClientRequest.<anonymous> (/home/justin/Git/link-inspector/dist/index.js:24:430695)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:519:28) {
  code: 'ERR_INVALID_PROTOCOL'
}

**Comment by justindhillon** [comment]
This is fixed in  #42
